kind = "web"
previewPath = "/"
title = "DragonzStore"
version = "1.0.0"
id = "artifacts/dragonzstore"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24046

[services.development]
run = "pnpm --filter @workspace/dragonzstore run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/dragonzstore", "run", "build" ]
publicDir = "artifacts/dragonzstore/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24046"
BASE_PATH = "/"
